#!/bin/bash

TARGET_DIR=~/mikro/fplib_target
export CXX_BIN_PATH=/usr/bin
export CXX_INCLUDE_PATH=/usr/include

script/find_tests
aclocal
autoheader
libtoolize
automake -a
autoconf
./configure --prefix=${TARGET_DIR} --exec-prefix=${TARGET_DIR}
make
make install

